mysql:
    build: ./dockerfile/mysql
    ports:
         - "3306:3306"
    volumes:
        - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
        - ./data/mysql/:/var/lib/mysql/:rw
        - ./log/mysql/:/var/log/mysql/:rw
    environment:
        MYSQL_ROOT_PASSWORD: "123456"
php-fpm:
    build: ./dockerfile/php-fpm
    expose:
        - "9000"
    volumes:
        - ./www:/var/www/html/:rw
        - ./log/php-fpm/:/var/log/php-fpm/:rw
        - ./conf/php-fpm/php.ini:/usr/local/etc/php/php.ini:rw
        - ./conf/php-fpm/conf.d:/usr/local/etc/php/conf.d/:rw
        - ./conf/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
        - ./conf/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    links:
        - mysql:mysql
nginx:
    build: ./dockerfile/nginx
    ports:
        - "80:80"
    volumes:
        - ./www:/usr/share/nginx/html:rw
        - ./log/nginx/:/var/log/nginx/:rw
        - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:rw
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    links:
        - php-fpm:php-fpm
redis:
    build: ./dockerfile/redis
    ports:
        - "6379:6379"
    volumes: 
    - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
elasticsearch:
    build: ./dockerfile/elasticsearch
    ports:
        - "9200:9200"
